---
title: "Homework 7"
author: "Emma Privett"
date: "2025-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
First, load in the packages and data set.
```{r, eval=TRUE,echo=TRUE}
library(dplyr)
library(tidyverse)
data(iris)
```
### Question 1
```{r, eval=TRUE,echo=TRUE}
glimpse(iris)
```

There are 150 observations of 5 variables in the iris data set.

### Question 2
```{r, eval=TRUE,echo=TRUE}
iris1 <- iris%>%
  filter(Species %in% c("versicolor", "virginica"),Sepal.Length>6, Sepal.Width>2.5)
glimpse(iris1)
```

There are 56 observations of 5 variables in iris1.

### Question 3
```{r, eval=TRUE,echo=TRUE}
iris2 <- iris1%>%
  select(Species, Sepal.Length, Sepal.Width)
glimpse(iris2)
```

There are 56 observations of 3 variables in iris2.

### Question 4
```{r, eval=TRUE,echo=TRUE}
iris3 <- iris2 %>%
  arrange(desc(Sepal.Length))
head(iris3)
```

### Question 5
```{r, eval=TRUE,echo=TRUE}
iris4 <- iris3 %>%
  mutate(Sepal.Area = Sepal.Length*Sepal.Width)
glimpse(iris4)
```

There are 56 observations of 4 variables in iris4.

### Question 6
```{r, eval=TRUE,echo=TRUE}
iris5 <- iris4 %>%
  summarise(Avg.Sepal.Length = mean(Sepal.Length), Avg.Sepal.Width=mean(Sepal.Width), Sample.Size= n())
print(iris5)
```

### Question 7
```{r, eval=TRUE,echo=TRUE}
iris6 <- iris4 %>%
  group_by(Species) %>%
  summarise(Avg.Sepal.Length = mean(Sepal.Length), Avg.Sepal.Width=mean(Sepal.Width), Sample.Size= n())
print(iris6)
```

### Question 8
```{r, eval=TRUE,echo=TRUE}
irisFinal <- iris %>%
  filter(Species %in% c("versicolor", "virginica"),Sepal.Length>6, Sepal.Width>2.5) %>%
  select(Species, Sepal.Length, Sepal.Width) %>%
  arrange(desc(Sepal.Length)) %>%
  mutate(Sepal.Area = Sepal.Length*Sepal.Width) %>%
  group_by(Species) %>%
  summarise(Avg.Sepal.Length = mean(Sepal.Length), Avg.Sepal.Width=mean(Sepal.Width), Sample.Size= n())
print(irisFinal)
```

### Question 9
```{r, eval=TRUE,echo=TRUE}
longiris <- iris %>%
  pivot_longer(cols=1:4, names_to="Measure", values_to="Value")
head(longiris)
```
